### ISSUE TITLE
KeyError: 'RWKV_JIT_ON'

### ISSUE THREAD

**Issue by bello7777** [Blealtan/RWKV-LM-LoRA#21]
hey, can you pls help 
want to test the fine tuning using the chat.py 
Loading...
Traceback (most recent call last):
  File "/home/ubuntu/Lora/RWKV-v4neo/chat22.py", line 6, in <module>
    from src.model_run import RWKV_RNN
  File "/home/ubuntu/Lora/RWKV-v4neo/src/model_run.py", line 23, in <module>
    if os.environ["RWKV_JIT_ON"] == '1':
  File "/home/ubuntu/anaconda3/envs/pytorch_p39/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'RWKV_JIT_ON'

**Comment by vision-zhao** [comment]
run `export RWKV_JIT_ON=1` before you run the code

**Comment by bello7777** [comment]
Thanks it worked however now I have keyerror 24

File = src/ model_run.py, line 243 in forward ww= w.blocks[i].att 
Keyerror 24

**Comment by bello7777** [comment]
solved it i needed to update a weight
