### ISSUE TITLE
size mismatch for emb.weight: copying a param with shape torch.Size([50277, 4096]) from checkpoint, the shape in current model is torch.Size([886, 4096])

### ISSUE THREAD

**Issue by aizpy** [Blealtan/RWKV-LM-LoRA#27]
run command as following:
```
python train.py \
--load_model ../../Models/rwkv-4-raven/RWKV-4-Raven-7B-v10x-Eng49%-Chn50%-Other1%-20230423-ctx4096.pth \
--proj_dir output/ \
--data_file data/rwkv.jsonl \
--vocab_size 50277 --ctx_len 4096 --epoch_steps 1000 --epoch_count 1000 --epoch_begin 0 --epoch_save 5 --micro_bsz 1 --n_layer 32 --n_embd 4096 --pre_ffn 0 --head_qk 0 --lr_init 1e-4 --lr_final 1e-4 --warmup_steps 0 --beta1 0.9 --beta2 0.999 --adam_eps 1e-8 --accelerator gpu --devices 1 --precision bf16 --strategy deepspeed_stage_2 --grad_cp 0 \
--lora --lora_r 8 --lora_alpha 16 --lora_dropout 0.01 \
--lora_parts=att,ffn,time,ln
```

output:
```
########## work in progress ##########
[2023-06-19 13:59:06,568] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)

############################################################################
#
# RWKV-4 BF16 on 1x1 GPU, bsz 1x1x1=1, deepspeed_stage_2
#
# Data = data/rwkv.jsonl (utf-8), ProjDir = output/
#
# Epoch = 0 to 999 (will continue afterwards), save every 5 epoch
#
# Each "epoch" = 1000 steps, 1000 samples, 4096000 tokens
#
# Model = 32 n_layer, 4096 n_embd, 4096 ctx_len
# LoRA = enabled, 8 r, 16.0 alpha, 0.01 dropout, on att,ffn,time,ln
#
# Adam = lr 0.0001 to 0.0001, warmup 0 steps, beta (0.9, 0.999), eps 1e-08
#
# Found torch 2.0.1+cu118, recommend 1.13.1+cu117 or newer
# Found deepspeed 0.9.4, recommend 0.7.0 (faster than newer versions)
# Found pytorch_lightning 1.9.0, recommend 1.9.1 or newer
#
############################################################################

{'load_model': '../../Models/rwkv-4-raven/RWKV-4-Raven-7B-v10x-Eng49%-Chn50%-Other1%-20230423-ctx4096.pth', 'wandb': '', 'proj_dir': 'output/', 'random_seed': -1, 'data_file': 'data/rwkv.jsonl', 'data_type': 'utf-8', 'vocab_size': 50277, 'ctx_len': 4096, 'epoch_steps': 1000, 'epoch_count': 1000, 'epoch_begin': 0, 'epoch_save': 5, 'micro_bsz': 1, 'n_layer': 32, 'n_embd': 4096, 'dim_att': 4096, 'dim_ffn': 16384, 'pre_ffn': 0, 'head_qk': 0, 'tiny_att_dim': 0, 'tiny_att_layer': -999, 'lr_init': 0.0001, 'lr_final': 0.0001, 'warmup_steps': 0, 'beta1': 0.9, 'beta2': 0.999, 'adam_eps': 1e-08, 'grad_cp': 0, 'my_pile_stage': 0, 'my_pile_shift': -1, 'my_pile_edecay': 0, 'layerwise_lr': 1, 'ds_bucket_mb': 200, 'my_img_version': 0, 'my_img_size': 0, 'my_img_bit': 0, 'my_img_clip': 'x', 'my_img_clip_scale': 1, 'my_img_l1_scale': 0, 'my_img_encoder': 'x', 'my_sample_len': 0, 'my_ffn_shift': 1, 'my_att_shift': 1, 'my_pos_emb': 0, 'load_partial': 0, 'magic_prime': 0, 'my_qa_mask': 0, 'my_testing': '', 'lora': True, 'lora_load': '', 'lora_r': 8, 'lora_alpha': 16.0, 'lora_dropout': 0.01, 'lora_parts': 'att,ffn,time,ln', 'logger': False, 'enable_checkpointing': False, 'default_root_dir': None, 'gradient_clip_val': 1.0, 'gradient_clip_algorithm': None, 'num_nodes': 1, 'num_processes': None, 'devices': '1', 'gpus': None, 'auto_select_gpus': None, 'tpu_cores': None, 'ipus': None, 'enable_progress_bar': True, 'overfit_batches': 0.0, 'track_grad_norm': -1, 'check_val_every_n_epoch': 100000000000000000000, 'fast_dev_run': False, 'accumulate_grad_batches': None, 'max_epochs': -1, 'min_epochs': None, 'max_steps': -1, 'min_steps': None, 'max_time': None, 'limit_train_batches': None, 'limit_val_batches': None, 'limit_test_batches': None, 'limit_predict_batches': None, 'val_check_interval': None, 'log_every_n_steps': 100000000000000000000, 'accelerator': 'gpu', 'strategy': 'deepspeed_stage_2', 'sync_batchnorm': False, 'precision': 'bf16', 'enable_model_summary': True, 'num_sanity_val_steps': 0, 'resume_from_checkpoint': None, 'profiler': None, 'benchmark': None, 'reload_dataloaders_every_n_epochs': 0, 'auto_lr_find': False, 'replace_sampler_ddp': False, 'detect_anomaly': False, 'auto_scale_batch_size': False, 'plugins': None, 'amp_backend': None, 'amp_level': None, 'move_metrics_to_cpu': False, 'multiple_trainloader_mode': 'max_size_cycle', 'inference_mode': True, 'my_timestamp': '2023-06-19-13-59-06', 'betas': (0.9, 0.999), 'real_bsz': 1, 'run_name': '50277 ctx4096 L32 D4096'}

RWKV_MY_TESTING
Using /home/aizpy/.cache/torch_extensions/py311_cu118 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/aizpy/.cache/torch_extensions/py311_cu118/wkv_4096_bf16/build.ninja...
Building extension module wkv_4096_bf16...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module wkv_4096_bf16...
Building token list...
Data has 35968 tokens, 886 vocab size.
  LoRA additionally training module blocks.0.ln1
  LoRA additionally training module blocks.0.ln2
  LoRA additionally training module blocks.0.ln0
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.0.att.key
  LoRA training module blocks.0.att.value
  LoRA training module blocks.0.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.0.ffn.key
  LoRA training module blocks.0.ffn.receptance
  LoRA training module blocks.0.ffn.value
  LoRA additionally training module blocks.1.ln1
  LoRA additionally training module blocks.1.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.1.att.key
  LoRA training module blocks.1.att.value
  LoRA training module blocks.1.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.1.ffn.key
  LoRA training module blocks.1.ffn.receptance
  LoRA training module blocks.1.ffn.value
  LoRA additionally training module blocks.2.ln1
  LoRA additionally training module blocks.2.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.2.att.key
  LoRA training module blocks.2.att.value
  LoRA training module blocks.2.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.2.ffn.key
  LoRA training module blocks.2.ffn.receptance
  LoRA training module blocks.2.ffn.value
  LoRA additionally training module blocks.3.ln1
  LoRA additionally training module blocks.3.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.3.att.key
  LoRA training module blocks.3.att.value
  LoRA training module blocks.3.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.3.ffn.key
  LoRA training module blocks.3.ffn.receptance
  LoRA training module blocks.3.ffn.value
  LoRA additionally training module blocks.4.ln1
  LoRA additionally training module blocks.4.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.4.att.key
  LoRA training module blocks.4.att.value
  LoRA training module blocks.4.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.4.ffn.key
  LoRA training module blocks.4.ffn.receptance
  LoRA training module blocks.4.ffn.value
  LoRA additionally training module blocks.5.ln1
  LoRA additionally training module blocks.5.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.5.att.key
  LoRA training module blocks.5.att.value
  LoRA training module blocks.5.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.5.ffn.key
  LoRA training module blocks.5.ffn.receptance
  LoRA training module blocks.5.ffn.value
  LoRA additionally training module blocks.6.ln1
  LoRA additionally training module blocks.6.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.6.att.key
  LoRA training module blocks.6.att.value
  LoRA training module blocks.6.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.6.ffn.key
  LoRA training module blocks.6.ffn.receptance
  LoRA training module blocks.6.ffn.value
  LoRA additionally training module blocks.7.ln1
  LoRA additionally training module blocks.7.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.7.att.key
  LoRA training module blocks.7.att.value
  LoRA training module blocks.7.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.7.ffn.key
  LoRA training module blocks.7.ffn.receptance
  LoRA training module blocks.7.ffn.value
  LoRA additionally training module blocks.8.ln1
  LoRA additionally training module blocks.8.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.8.att.key
  LoRA training module blocks.8.att.value
  LoRA training module blocks.8.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.8.ffn.key
  LoRA training module blocks.8.ffn.receptance
  LoRA training module blocks.8.ffn.value
  LoRA additionally training module blocks.9.ln1
  LoRA additionally training module blocks.9.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.9.att.key
  LoRA training module blocks.9.att.value
  LoRA training module blocks.9.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.9.ffn.key
  LoRA training module blocks.9.ffn.receptance
  LoRA training module blocks.9.ffn.value
  LoRA additionally training module blocks.10.ln1
  LoRA additionally training module blocks.10.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.10.att.key
  LoRA training module blocks.10.att.value
  LoRA training module blocks.10.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.10.ffn.key
  LoRA training module blocks.10.ffn.receptance
  LoRA training module blocks.10.ffn.value
  LoRA additionally training module blocks.11.ln1
  LoRA additionally training module blocks.11.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.11.att.key
  LoRA training module blocks.11.att.value
  LoRA training module blocks.11.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.11.ffn.key
  LoRA training module blocks.11.ffn.receptance
  LoRA training module blocks.11.ffn.value
  LoRA additionally training module blocks.12.ln1
  LoRA additionally training module blocks.12.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.12.att.key
  LoRA training module blocks.12.att.value
  LoRA training module blocks.12.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.12.ffn.key
  LoRA training module blocks.12.ffn.receptance
  LoRA training module blocks.12.ffn.value
  LoRA additionally training module blocks.13.ln1
  LoRA additionally training module blocks.13.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.13.att.key
  LoRA training module blocks.13.att.value
  LoRA training module blocks.13.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.13.ffn.key
  LoRA training module blocks.13.ffn.receptance
  LoRA training module blocks.13.ffn.value
  LoRA additionally training module blocks.14.ln1
  LoRA additionally training module blocks.14.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.14.att.key
  LoRA training module blocks.14.att.value
  LoRA training module blocks.14.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.14.ffn.key
  LoRA training module blocks.14.ffn.receptance
  LoRA training module blocks.14.ffn.value
  LoRA additionally training module blocks.15.ln1
  LoRA additionally training module blocks.15.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.15.att.key
  LoRA training module blocks.15.att.value
  LoRA training module blocks.15.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.15.ffn.key
  LoRA training module blocks.15.ffn.receptance
  LoRA training module blocks.15.ffn.value
  LoRA additionally training module blocks.16.ln1
  LoRA additionally training module blocks.16.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.16.att.key
  LoRA training module blocks.16.att.value
  LoRA training module blocks.16.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.16.ffn.key
  LoRA training module blocks.16.ffn.receptance
  LoRA training module blocks.16.ffn.value
  LoRA additionally training module blocks.17.ln1
  LoRA additionally training module blocks.17.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.17.att.key
  LoRA training module blocks.17.att.value
  LoRA training module blocks.17.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.17.ffn.key
  LoRA training module blocks.17.ffn.receptance
  LoRA training module blocks.17.ffn.value
  LoRA additionally training module blocks.18.ln1
  LoRA additionally training module blocks.18.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.18.att.key
  LoRA training module blocks.18.att.value
  LoRA training module blocks.18.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.18.ffn.key
  LoRA training module blocks.18.ffn.receptance
  LoRA training module blocks.18.ffn.value
  LoRA additionally training module blocks.19.ln1
  LoRA additionally training module blocks.19.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.19.att.key
  LoRA training module blocks.19.att.value
  LoRA training module blocks.19.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.19.ffn.key
  LoRA training module blocks.19.ffn.receptance
  LoRA training module blocks.19.ffn.value
  LoRA additionally training module blocks.20.ln1
  LoRA additionally training module blocks.20.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.20.att.key
  LoRA training module blocks.20.att.value
  LoRA training module blocks.20.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.20.ffn.key
  LoRA training module blocks.20.ffn.receptance
  LoRA training module blocks.20.ffn.value
  LoRA additionally training module blocks.21.ln1
  LoRA additionally training module blocks.21.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.21.att.key
  LoRA training module blocks.21.att.value
  LoRA training module blocks.21.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.21.ffn.key
  LoRA training module blocks.21.ffn.receptance
  LoRA training module blocks.21.ffn.value
  LoRA additionally training module blocks.22.ln1
  LoRA additionally training module blocks.22.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.22.att.key
  LoRA training module blocks.22.att.value
  LoRA training module blocks.22.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.22.ffn.key
  LoRA training module blocks.22.ffn.receptance
  LoRA training module blocks.22.ffn.value
  LoRA additionally training module blocks.23.ln1
  LoRA additionally training module blocks.23.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.23.att.key
  LoRA training module blocks.23.att.value
  LoRA training module blocks.23.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.23.ffn.key
  LoRA training module blocks.23.ffn.receptance
  LoRA training module blocks.23.ffn.value
  LoRA additionally training module blocks.24.ln1
  LoRA additionally training module blocks.24.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.24.att.key
  LoRA training module blocks.24.att.value
  LoRA training module blocks.24.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.24.ffn.key
  LoRA training module blocks.24.ffn.receptance
  LoRA training module blocks.24.ffn.value
  LoRA additionally training module blocks.25.ln1
  LoRA additionally training module blocks.25.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.25.att.key
  LoRA training module blocks.25.att.value
  LoRA training module blocks.25.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.25.ffn.key
  LoRA training module blocks.25.ffn.receptance
  LoRA training module blocks.25.ffn.value
  LoRA additionally training module blocks.26.ln1
  LoRA additionally training module blocks.26.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.26.att.key
  LoRA training module blocks.26.att.value
  LoRA training module blocks.26.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.26.ffn.key
  LoRA training module blocks.26.ffn.receptance
  LoRA training module blocks.26.ffn.value
  LoRA additionally training module blocks.27.ln1
  LoRA additionally training module blocks.27.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.27.att.key
  LoRA training module blocks.27.att.value
  LoRA training module blocks.27.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.27.ffn.key
  LoRA training module blocks.27.ffn.receptance
  LoRA training module blocks.27.ffn.value
  LoRA additionally training module blocks.28.ln1
  LoRA additionally training module blocks.28.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.28.att.key
  LoRA training module blocks.28.att.value
  LoRA training module blocks.28.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.28.ffn.key
  LoRA training module blocks.28.ffn.receptance
  LoRA training module blocks.28.ffn.value
  LoRA additionally training module blocks.29.ln1
  LoRA additionally training module blocks.29.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.29.att.key
  LoRA training module blocks.29.att.value
  LoRA training module blocks.29.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.29.ffn.key
  LoRA training module blocks.29.ffn.receptance
  LoRA training module blocks.29.ffn.value
  LoRA additionally training module blocks.30.ln1
  LoRA additionally training module blocks.30.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.30.att.key
  LoRA training module blocks.30.att.value
  LoRA training module blocks.30.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.30.ffn.key
  LoRA training module blocks.30.ffn.receptance
  LoRA training module blocks.30.ffn.value
  LoRA additionally training module blocks.31.ln1
  LoRA additionally training module blocks.31.ln2
  LoRA additionally training parameter time_decay
  LoRA additionally training parameter time_first
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_v
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.31.att.key
  LoRA training module blocks.31.att.value
  LoRA training module blocks.31.att.receptance
  LoRA additionally training parameter time_mix_k
  LoRA additionally training parameter time_mix_r
  LoRA training module blocks.31.ffn.key
  LoRA training module blocks.31.ffn.receptance
  LoRA training module blocks.31.ffn.value
########## Loading ../../Models/rwkv-4-raven/RWKV-4-Raven-7B-v10x-Eng49%-Chn50%-Other1%-20230423-ctx4096.pth... ##########
Traceback (most recent call last):
  File "/home/aizpy/Workspace/NLP/RWKV-LM-LoRA/RWKV-v4neo/train.py", line 347, in <module>
    model.load_state_dict(load_dict, strict=(not args.lora))
  File "/home/aizpy/anaconda3/envs/rwkv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for RWKV:
        size mismatch for emb.weight: copying a param with shape torch.Size([50277, 4096]) from checkpoint, the shape in current model is torch.Size([886, 4096]).
        size mismatch for head.weight: copying a param with shape torch.Size([50277, 4096]) from checkpoint, the shape in current model is torch.Size([886, 4096]).
```

**Comment by Blealtan** [comment]
Don't do this. Convert your jsonl to binidx (see [here](https://github.com/Abel2076/json2binidx_tool) and use binidx data format.
