### ISSUE TITLE
New model World run error, is it support new vocab 'rwkv_vocab_v20230424.txt'?

### ISSUE THREAD

**Issue by Helloworld2345567** [Blealtan/RWKV-LM-LoRA#43]
When I finish lora training and run 'python chat.py', 
Traceback (most recent call last):
  File "/root/data1/ym/RWKV-LM/RWKV-LM-LoRA/RWKV-v4neo/chat.py", line 28, in <module>
    tokenizer = TOKENIZER(WORD_NAME, UNKNOWN_CHAR=UNKNOWN_CHAR)
  File "/root/data1/ym/RWKV-LM/RWKV-LM-LoRA/RWKV-v4neo/src/utils.py", line 22, in __init__
    self.tokenizer = PreTrainedTokenizerFast(tokenizer_file=WORD_NAME[0])
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 111, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: invalid type: integer `1`, expected struct Tokenizer at line 1 column 1

**Comment by Helloworld2345567** [comment]
**Title:** Update TOKENIZER class and load vocabulary from ChatRWKV

**Body:**
  
To resolve the issue, make the following changes in the code:
  
1. Replace the `TOKENIZER` class in `RWKV-LM-LoRA/RWKV-v4neo/src/utils.py` with the `TOKENIZER` class from `ChatRWKV/src/utils.py`.
  
2. Update the vocabulary loading code in `ChatRWKV/v2/chat.py` with the following:
  
   ```python
   from rwkv.model import RWKV
   from rwkv.utils import PIPELINE
   
   if 'world/' in args.MODEL_NAME or '-World-' in args.MODEL_NAME:
       pipeline = PIPELINE(model, "rwkv_vocab_v20230424")
       END_OF_TEXT = 0
       END_OF_LINE = 11
   ```
  
3. Replace any instances of `tokenizer.tokenizer.    method` with `pipeline.    method` in the code.
  
Or you can merge lora weights with original weights. Then you don't catch this issues.
