### ISSUE TITLE
ninja: no work to do

### ISSUE THREAD

**Issue by ByUnal** [Blealtan/RWKV-LM-LoRA#55]
What cause this problem ? I installed all the necessary libraries.

```
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/bdemirel/anaconda3/envs/cht-rwkv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/bdemirel/anaconda3/envs/cht-rwkv/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bdemirel/rwkv-cht/RWKV-LM/RWKV-v4neo/train.py", line 322, in <module>
    from src.model import RWKV
  File "/home/bdemirel/rwkv-cht/RWKV-LM/RWKV-v4neo/src/model.py", line 46, in <module>
    wkv_cuda = load(name=f"wkv_{T_MAX}_bf16", sources=["cuda/wkv_op_bf16.cpp", "cuda/wkv_cuda_bf16.cu"], verbose=True, extra_cuda_cflags=["-t 4", "-std=c++17", "-res-usage", "--maxrregcount 60", "--use_fast_math", "-O3", "-Xptxas -O3", "--extra-device-vectorization", f"-DTmax={T_MAX}"])
  File "/home/bdemirel/anaconda3/envs/cht-rwkv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/bdemirel/anaconda3/envs/cht-rwkv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/bdemirel/anaconda3/envs/cht-rwkv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/bdemirel/anaconda3/envs/cht-rwkv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'wkv_1024_bf16'

```

**Comment by ByUnal** [comment]
Cell execution is completed in this way, and then nothing happens

![image](https://github.com/Blealtan/RWKV-LM-LoRA/assets/43930582/2ac41726-5073-4829-b193-08567200fc16)
